platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'BMKMapView-Inertia_Example' do
  pod 'BMKMapView-Inertia', :path => '../'

  target 'BMKMapView-Inertia_Tests' do
    inherit! :search_paths
    
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
